apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dpsim-demo.fullname" . }}
  labels:
    {{- include "dpsim-demo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dpsim-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dpsim-demo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dpsim-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
           #- name: config-volume
           #  mountPath: /dpsim/Configs/shmem_CIGRE_MV_PF/Shmem_CIGRE_MV.conf
           #  subPath: Shmem_CIGRE_MV.conf
           #  TODO there seems to be an issue with subPath mounting of particular files into existing directories
           #  fixed by postStart hook work-around below 
           #  should be changed back when the issue is fixed
          - name: config-volume
            mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # overcome issues with subpath mount by mounting config elsewhere and copying it over
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /config/Shmem_CIGRE_MV.conf /dpsim/Configs/shmem_CIGRE_MV_PF/Shmem_CIGRE_MV.conf
      volumes:
        - name: config-volume
          configMap:
            name: dpsim-demo-villas-configmap-{{ .Release.Name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
