apiVersion: v1
kind: Service
metadata:
  name: {{ include "dpsim-demo.fullname" . }}
  labels:
    {{- include "dpsim-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: iec104
      protocol: TCP
      name: iec104
  selector:
    {{- include "dpsim-demo.selectorLabels" . | nindent 4 }}
