apiVersion: v1
kind: Service
metadata:
  name: {{ include "fledge-demo.fullname" . }}
  labels:
    {{- include "fledge-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: fledge
      protocol: TCP
      name: fledge
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "fledge-demo.selectorLabels" . | nindent 4 }}
